name: Setup
description: Setup Node.js and install dependencies

inputs:
  registry-url:
    description: Optional npm registry URL for setup-node
    required: false
    default: https://registry.npmjs.org/

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        registry-url: ${{ inputs.registry-url }}
        cache: yarn
        cache-dependency-path: yarn.lock

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
