import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export interface ContextSummaryCardProps {
  title: string;
  description: string;
  variant?: string;
  children?: React.ReactNode;
}

/**
 * Generated by Amaryllis Components Generator
 * Spec Version: 1.0.0
 * Spec Hash: example-artifact
 * Model: deterministic-generator
 * Prompt Version: none
 * Validation: schema-and-policy-passed
 * Generated At: 2026-05-16T00:00:00.000Z
 * Previous Diff: available through the customize command
 */
export const ContextSummaryCard: React.FC<ContextSummaryCardProps> = ({
  title,
  description,
  variant,
}) => {
  switch (variant) {
    case 'compact':
      return (
        <View style={[styles.card, styles.compactCard]}>
          <Text style={styles.eyebrow}>AI component</Text>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.description}>{description}</Text>
        </View>
      );
    default:
      return (
        <View style={styles.card}>
          <Text style={styles.eyebrow}>AI component</Text>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.description}>{description}</Text>
        </View>
      );
  }
};

const styles = StyleSheet.create({
  card: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#eef4ff',
  },
  compactCard: {
    backgroundColor: '#f3f4f6',
  },
  eyebrow: {
    marginBottom: 4,
    color: '#2563eb',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  title: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '700',
  },
  description: {
    marginTop: 4,
    color: '#374151',
    fontSize: 14,
  },
});
