import type { ValidatedComponentSpec } from '../schema/spec.schema';

export class ReactGenerator {
  generate(spec: ValidatedComponentSpec): string {
    const { metadata, props, ui, target } = spec;
    const componentName = this.toPascalCase(metadata.name);

    const propsType = this.generatePropsType(props, ui?.slots);
    const layout = ui?.layout || '<div>{children}</div>';

    const imports = this.generateImports(target.runtime);

    const propKeys = [
      ...Object.keys(props.properties),
      ...(ui?.slots || []),
      'children',
    ];

    return `
${imports}

export interface ${componentName}Props ${propsType}

/**
 * Generated by Amaryllis Components Generator
 * Spec Version: ${metadata.version}
 */
export const ${componentName}: React.FC<${componentName}Props> = ({
  ${propKeys.join(',\n  ')}
}) => {
  return (
    ${this.wrapWithLayout(layout, ui?.slots)}
  );
};
`;
  }

  private toPascalCase(str: string): string {
    return str
      .replace(new RegExp(/[-_]+/, 'g'), ' ')
      .replace(new RegExp(/[^\w\s]/, 'g'), '')
      .replace(
        new RegExp(/\s+(.)(\w*)/, 'g'),
        (_$1, $2, $3) => `${$2.toUpperCase() + $3.toLowerCase()}`
      )
      .replace(new RegExp(/\w/), (s) => s.toUpperCase());
  }

  private generatePropsType(props: any, slots?: string[]): string {
    const lines = Object.entries(props.properties).map(
      ([key, schema]: [string, any]) => {
        const isRequired = props.required?.includes(key);
        const type = this.jsonSchemaToTsType(schema);
        return `  ${key}${isRequired ? '' : '?'}: ${type};`;
      }
    );

    if (slots) {
      slots.forEach((slot) => {
        lines.push(`  ${slot}?: React.ReactNode;`);
      });
    }

    return `{
${lines.join('\n')}
  children?: React.ReactNode;
}`;
  }

  private jsonSchemaToTsType(schema: any): string {
    switch (schema.type) {
      case 'string':
        return 'string';
      case 'number':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'array':
        return 'any[]';
      case 'object':
        return 'Record<string, any>';
      default:
        return 'any';
    }
  }

  private generateImports(runtime: string): string {
    if (runtime === 'rn') {
      return "import React from 'react';\nimport { View, Text } from 'react-native';";
    }
    return "import React from 'react';";
  }

  private wrapWithLayout(layout: string, slots?: string[]): string {
    // Basic substitution for slots if they exist in layout as {slotName}
    let result = layout;
    if (slots) {
      slots.forEach((slot) => {
        // Replace both {slot} and {slots.slot} for flexibility
        result = result.split(`{${slot}}`).join(`{${slot}}`);
        result = result.split(`{slots.${slot}}`).join(`{${slot}}`);
      });
    }
    return result;
  }
}
