import type { ValidatedComponentSpec } from '../schema/spec.schema';
import type { JsonSchemaValue } from '../types/spec';

export interface ReactGeneratorOptions {
  specHash?: string;
  modelId?: string;
  promptVersion?: string;
  validationSummary?: string;
  generatedAt?: Date;
}

type ComponentVariants = NonNullable<ValidatedComponentSpec['ui']>['variants'];
type ComponentDesignTokens = NonNullable<
  ValidatedComponentSpec['ui']
>['designTokens'];

export class ReactGenerator {
  generate(
    spec: ValidatedComponentSpec,
    options: ReactGeneratorOptions = {}
  ): string {
    const { metadata, props, ui, target } = spec;
    const componentName = this.toPascalCase(metadata.name);

    const propsType = this.generatePropsType(
      props,
      ui?.slots,
      ui?.designTokens
    );
    const layout = ui?.layout || '<div>{children}</div>';

    const imports = this.generateImports(target.runtime);

    const propKeys = [
      ...Object.keys(props.properties),
      ...(ui?.slots || []),
      ...(ui?.designTokens ? ['designTokens'] : []),
      'variant',
      'children',
    ];

    const variantLogic = this.generateVariantLogic(ui?.variants, layout);
    const provenance = this.generateProvenance(metadata.version, options);

    return `
${imports}

export interface ${componentName}Props ${propsType}

/**
 * Generated by Amaryllis Components Generator
${provenance}
 */
export const ${componentName}: React.FC<${componentName}Props> = ({
  ${propKeys.join(',\n  ')}
}) => {
  ${variantLogic}
};
`;
  }

  private generateVariantLogic(
    variants: ComponentVariants,
    defaultLayout: string = '<div>{children}</div>'
  ): string {
    if (!variants || Object.keys(variants).length === 0) {
      return `return (\n    ${this.wrapWithLayout(defaultLayout)}\n  );`;
    }

    const cases = Object.entries(variants).map(([name, config]) => {
      const layout = config.layout || defaultLayout;
      return `    case '${name}':\n      return (\n        ${this.wrapWithLayout(layout)}\n      );`;
    });

    return `switch (variant) {
${cases.join('\n')}
    default:
      return (\n        ${this.wrapWithLayout(defaultLayout)}\n      );
  }`;
  }

  private toPascalCase(str: string): string {
    return str
      .replace(new RegExp(/[-_]+/, 'g'), ' ')
      .replace(new RegExp(/[^\w\s]/, 'g'), '')
      .replace(
        new RegExp(/\s+(.)(\w*)/, 'g'),
        (_$1, $2, $3) => `${$2.toUpperCase() + $3.toLowerCase()}`
      )
      .replace(new RegExp(/\w/), (s) => s.toUpperCase());
  }

  private generatePropsType(
    props: ValidatedComponentSpec['props'],
    slots?: string[],
    designTokens?: ComponentDesignTokens
  ): string {
    const lines = Object.entries(props.properties).map(([key, schema]) => {
      const isRequired = props.required?.includes(key);
      const type = this.jsonSchemaToTsType(schema);
      return `  ${key}${isRequired ? '' : '?'}: ${type};`;
    });

    if (slots) {
      slots.forEach((slot) => {
        lines.push(`  ${slot}?: React.ReactNode;`);
      });
    }

    const designTokenType = this.generateDesignTokensType(designTokens);
    if (designTokenType) {
      lines.push(`  designTokens?: ${designTokenType};`);
    }

    return `{
${lines.join('\n')}
  variant?: string;
  children?: React.ReactNode;
}`;
  }

  private generateDesignTokensType(
    designTokens?: ComponentDesignTokens
  ): string | null {
    if (!designTokens) {
      return null;
    }

    const groups = [
      this.generateDesignTokenGroupType('spacing', designTokens.spacing),
      this.generateDesignTokenGroupType('typography', designTokens.typography),
      this.generateDesignTokenGroupType('colorRoles', designTokens.colorRoles),
    ].filter((line): line is string => Boolean(line));

    if (groups.length === 0) {
      return null;
    }

    return `{
${groups.join('\n')}
  }`;
  }

  private generateDesignTokenGroupType(
    groupName: string,
    tokens?: string[]
  ): string | null {
    if (!tokens || tokens.length === 0) {
      return null;
    }

    const tokenLines = tokens.map((token) => `      ${token}?: string;`);

    return `    ${groupName}?: {
${tokenLines.join('\n')}
    };`;
  }

  private jsonSchemaToTsType(schema: JsonSchemaValue): string {
    switch (schema.type) {
      case 'string':
        return 'string';
      case 'number':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'array':
        return 'unknown[]';
      case 'object':
        return 'Record<string, unknown>';
      default:
        return 'unknown';
    }
  }

  private generateImports(runtime: string): string {
    if (runtime === 'rn') {
      return "import React from 'react';\nimport { View, Text } from 'react-native';";
    }
    return "import React from 'react';";
  }

  private wrapWithLayout(layout: string, slots?: string[]): string {
    // Basic substitution for slots if they exist in layout as {slotName}
    let result = layout;
    if (slots) {
      slots.forEach((slot) => {
        // Replace both {slot} and {slots.slot} for flexibility
        result = result.split(`{${slot}}`).join(`{${slot}}`);
        result = result.split(`{slots.${slot}}`).join(`{${slot}}`);
      });
    }
    return result;
  }

  private generateProvenance(
    specVersion: string,
    options: ReactGeneratorOptions
  ): string {
    return [
      ` * Spec Version: ${specVersion}`,
      ` * Spec Hash: ${options.specHash ?? 'unavailable'}`,
      ` * Model: ${options.modelId ?? 'deterministic-generator'}`,
      ` * Prompt Version: ${options.promptVersion ?? 'none'}`,
      ` * Validation: ${options.validationSummary ?? 'policy-passed'}`,
      ` * Generated At: ${(options.generatedAt ?? new Date()).toISOString()}`,
      ' * Previous Diff: available through the customize command',
    ].join('\n');
  }
}
