import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { ReactGenerator } from '../generator/react';
import type { ValidatedComponentSpec } from '../schema/spec.schema';

const GENERATED_AT = new Date('2026-01-01T00:00:00.000Z');
const GENERATION_OPTIONS = {
  specHash: 'sha256:fixture-spec',
  generatorVersion: '0.1.0-test',
  modelId: 'fixture-model',
  promptVersion: 'fixture-prompt-v1',
  validationSummary: 'schema-and-policy-passed',
  generatedAt: GENERATED_AT,
};

type Runtime = ValidatedComponentSpec['target']['runtime'];

function runtimeComponentName(runtime: Runtime): string {
  switch (runtime) {
    case 'rn':
      return 'native';
    case 'nextjs':
      return 'next';
    default:
      return 'web';
  }
}

function createRepresentativeSpec(runtime: Runtime): ValidatedComponentSpec {
  return {
    apiVersion: 'amaryllis/v1alpha1',
    kind: 'ComponentSpec',
    metadata: {
      name: `deterministic-${runtimeComponentName(runtime)}-card`,
      version: '1.2.3',
    },
    props: {
      type: 'object',
      properties: {
        title: { type: 'string', default: 'Untitled' },
        enabled: { type: 'boolean', default: true },
        count: { type: 'integer', default: 3 },
        tags: {
          type: 'array',
          items: { type: 'string' },
          default: ['stable', 'generated'],
        },
        settings: {
          type: 'object',
          properties: {
            theme: {
              type: 'string',
              enum: ['light', 'dark'],
              default: 'light',
            },
            retries: { type: 'integer', default: 1 },
          },
          required: ['theme'],
          default: { theme: 'light', retries: 1 },
        },
      },
      required: ['title'],
    },
    target: { framework: 'react', runtime },
    ai: { mode: 'scaffold', execution: 'build' },
  };
}

function readGolden(runtime: Runtime): string {
  return readFileSync(
    join(__dirname, 'goldens', `react-${runtime}.golden.txt`),
    'utf8'
  );
}

describe('ReactGenerator deterministic golden output', () => {
  const generator = new ReactGenerator();

  it.each<Runtime>(['web', 'nextjs', 'rn'])(
    'matches the committed %s golden output',
    (runtime) => {
      const spec = createRepresentativeSpec(runtime);
      const first = generator.generate(spec, GENERATION_OPTIONS);
      const second = generator.generate(spec, GENERATION_OPTIONS);

      expect(first).toBe(second);
      expect(first).toBe(readGolden(runtime));
    }
  );

  it('accepts defaults without emitting runtime default behavior', () => {
    const code = generator.generate(
      createRepresentativeSpec('web'),
      GENERATION_OPTIONS
    );

    expect(code).not.toContain('Untitled');
    expect(code).not.toContain('default:');
  });

  it('emits deterministic provenance metadata', () => {
    const code = generator.generate(
      createRepresentativeSpec('web'),
      GENERATION_OPTIONS
    );
    const provenance = code.match(/\/\*\*[\s\S]*?\*\//)?.[0];

    expect(provenance).toBe(`/**
 * Generated by Amaryllis Components Generator
 * Spec Version: 1.2.3
 * Spec Hash: sha256:fixture-spec
 * Generator Version: 0.1.0-test
 * Model: fixture-model
 * Prompt Version: fixture-prompt-v1
 * Validation: schema-and-policy-passed
 * Generated At: 2026-01-01T00:00:00.000Z
 * Previous Diff: available through the customize command
 */`);
  });
});
